### ISSUE TITLE
Library is broken from 1.0.1 to 1.0.2

### ISSUE THREAD

**Issue by FireZenk** [florent37/ViewAnimator#11]
animation = ViewAnimator
                .animate(logo).scaleX(0, 1).scaleY(0, 1).alpha(0, 1).descelerate().duration(500)
                .thenAnimate(logo).scaleX(1, 0).scaleY(1, 0).alpha(1, 0).accelerate().duration(500);

descelerate cannot exists...

**Comment by FireZenk** [comment]
Also you deleted 1.0.1 from maven repo...

**Comment by florent37** [comment]
yes it's a mistake, I deleted those methods on a merge

**Comment by florent37** [comment]
should be fixed on 1.0.3
