### ISSUE TITLE
rotation can't  animate

### ISSUE THREAD

**Issue by doulala1986** [florent37/ViewAnimator#19]
`
 private View.OnClickListener onViewClickListener = new View.OnClickListener() {

        @Override
        public void onClick(View v) {
            if(v==btn)
            ViewAnimator.animate(img).rotation(360).start();
        }
    };
`

it works when i click the btn first time, but will never work after animation finished. I'm sure this statement is executed.

**Comment by florent37** [comment]
I think it animate to 360, and if you click again the view.rotation is already = 360, so no animation required,
maybe just a method `ViewAnimator.animate(img).rotation(0, 360).start();` should be better ?

**Comment by doulala1986** [comment]
this  is much useful for me。thanks a lot~~

**Comment by florent37** [comment]
👍
