### ISSUE TITLE
Can I stop the animation?

### ISSUE THREAD

**Issue by Jimweb3** [florent37/ViewAnimator#27]
when I set repeat count , like 200 , then view repeats 100 ,  I want stop it , How can I do ?

**Comment by shahimclt** [comment]
This was added in 9809cd49131ad9dda503606fe762656dcd607b9b. Implementation can be found in sample.

    final ViewAnimator viewAnimator = ViewAnimator.animate(mountain, image)
        ....
        ....
        .start();

    new Handler(Looper.getMainLooper()).postDelayed(new Runnable() {
        @Override
        public void run() {
            viewAnimator.cancel();
        }
    }, 3000);
