### ISSUE TITLE
Stop animation

### ISSUE THREAD

**Issue by danielpassos** [florent37/ViewAnimator#38]
There is a way (method) to stop an animation started?

**Comment by sandeep2242** [comment]
I am also having the same issue but I solved using a workaround, I was changing different colors and now I have set only a default color. Still its animating but it doesn't shows.

**Comment by efraespada** [comment]
@danielpassos @sandeep2242 ViewAnimator methods always return a ViewAnimator object you can instance:
```java
ViewAnimator animation = ViewAnimator.animate(holder.active)
   .waitForHeight()
   .duration(1000)
   .fadeIn()
   .repeatCount(android.view.animation.Animation.INFINITE)
   .start();
            
animation.cancel();
```
