### ISSUE TITLE
repeatMode(ValueAnimator.INFINITE) doesn't work

### ISSUE THREAD

**Issue by NayMak** [florent37/ViewAnimator#42]
Hello,

Here is my code:

```
ViewAnimator viewAnimator = ViewAnimator.animate(textView)
                .tada()
                .duration(4000)
                .repeatMode(ValueAnimator.INFINITE)
                .start();
```

The animation works but the 'ValueAnimator.INFINITE' value (which is an enum that is equal to "-1") doesn't work to make the animation loop indefinitely.

Could someone help me to find the issue?

**Comment by florent37** [comment]
use .repeatCount(ValueAnimator.INFINITE)
and .repeatMode(ValueAnimator.RESTART) (or REVERSE)

**Comment by NayMak** [comment]
It works! Thank you!

**Comment by florent37** [comment]
;)

**Comment by TurKurT656** [comment]
How to add delay between loops?

**Comment by NayMak** [comment]
@TurKurT656 I think you need to open a new issue if you want to ask news questions 😊
This topic is closed anyway
