### ISSUE TITLE
Log.d(null, "path: value=" + value + ", x=" + x + ", y=" + y); 

### ISSUE THREAD

**Issue by CodeK1988** [florent37/ViewAnimator#48]
Log.d(null, "path: value=" + value + ", x=" + x + ", y=" + y);
please close log.

**Comment by liyujiang-gzu** [comment]
you can contribute some codes and  create a Pull Requests.

**Comment by liyujiang-gzu** [comment]
@yizuochengchi 老铁，你可以fork代码去修改了再推送上来请求作者合入。
