### ISSUE TITLE
i got a memory leak with Animator$AnimatorListener

### ISSUE THREAD

**Issue by LiveSalton** [florent37/ViewAnimator#49]
* android.arch.lifecycle.ReportFragment has leaked:
* static Choreographer.!(mMainInstance)!
* ↳ Choreographer.!(mCallbackQueues)!
* ↳ array Choreographer$CallbackQueue[].!([1])!
* ↳ Choreographer$CallbackQueue.!(mHead)!
* ↳ Choreographer$CallbackRecord.!(action)!
* ↳ AnimationHandler$1.!(this$0)! (anonymous implementation of android.view.Choreographer$FrameCallback)
* ↳ AnimationHandler.!(mAnimationCallbacks)!
* ↳ ArrayList.!(elementData)!
* ↳ array Object[].!([2])!
* ↳ AnimatorSet.!(mListeners)!
* ↳ ArrayList.!(elementData)!
* ↳ array Object[].!([0])!
* ↳ ViewAnimator$1.!(this$0)! (anonymous implementation of android.animation.Animator$AnimatorListener)
* ↳ ViewAnimator.!(animationList)!
* ↳ ArrayList.!(elementData)!
* ↳ array Object[].!([0])!
* ↳ AnimationBuilder.!(views)!
* ↳ array View[].!([0])!
* ↳ AppCompatImageView.mContext
* ↳ PerformanceAty.mFragments
* ↳ FragmentController.mHost
* ↳ Activity$HostCallbacks.mFragmentManager
* ↳ FragmentManagerImpl.mAdded
* ↳ ArrayList.elementData
* ↳ array Object[].[0]
* ↳ ReportFragment

my code is :

    public static void viewScaleButtonAnimation(View... view) {
        ViewAnimator.animate(view).scale(1, 1.05f, 1).duration(3000)
                .repeatCount(-1).start();
    }

how can i release this anim??

**Comment by liyujiang-gzu** [comment]
```java
ViewAnimator viewAnimator = ViewAnimator.animate(view).scale(1, 1.05f, 1).duration(3000)
            .repeatCount(-1)
viewAnimator.start();
```   
add method in ViewAnimator:
```java
    public void pause() {
        if (this.animatorSet != null) {
            if (Build.VERSION.SDK_INT >= 19) {
                this.animatorSet.pause();
            }
        } else if (this.prev != null) {
            this.prev.pause();
        }
    }

    public void resume() {
        if (this.animatorSet != null) {
            if (Build.VERSION.SDK_INT >= 19) {
                this.animatorSet.resume();
            }
        } else if (this.prev != null) {
            this.prev.resume();
        }
    }
```
when onPause/onResume/onDestroy, try this:
```java
viewAnimator.pause();
viewAnimator.resume();
viewAnimator.cance();
```
I don't know whether this can be solved.

**Comment by liyujiang-gzu** [comment]
如果通过pause、resume、cance可以解决内存泄露问题，那么，可以在ViewAnimator里加一个方法来自动维护生命周期，如：
```java
public ViewAnimator attachLifecycle(LifecycleOwner owner) {
    owner.getLifecycle().addObserver(this);
    return this;
}
```
```java
    @OnLifecycleEvent(Lifecycle.Event.ON_ANY)
    public void onAny(LifecycleOwner source, Lifecycle.Event event) {
        if (event == Lifecycle.Event.ON_RESUME) {
            resume();
        } else if (event == Lifecycle.Event.ON_PAUSE) {
            pause();
        } else if (event == Lifecycle.Event.ON_DESTROY) {
            cance();
            source.getLifecycle().removeObserver(this);
        }
    }

```

**Comment by LiveSalton** [comment]
好的，非常感谢你的方法。我已经处理好内存泄漏的问题。

**Comment by liyujiang-gzu** [comment]
> 
> 
> 好的，非常感谢你的方法。我已经处理好内存泄漏的问题。

老铁，你是怎么处理的？

**Comment by xmutzlq** [comment]
泄漏怎么处理的？
