### ISSUE TITLE
consider migrating to maven or jitpack

### ISSUE THREAD

**Issue by yamin8000** [florent37/ViewAnimator#62]
@florent37 
jCenter is currently deprecated and artifacts can only be downloaded till 2022-02-01, consider migrating to jitpack or maven central.
[more info here](https://developer.android.com/studio/build/jcenter-migration)

**Comment by vijay81** [comment]
@florent37 Please look into this issue and do migrate to jetpack or maven central.

**Comment by supersu-man** [comment]
Use this, `implementation 'com.github.florent37:ViewAnimator:v1.1.2'`

**Comment by duxiahui** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
